name: Frontend PR Build Check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "Our_Chruch_Website/**"

jobs:
  frontend-build:
    uses: ./.github/workflows/frontend_build.yml
